{
 "title": "IoT Dashboard V2",
 "description": "Dashboard for metrics jmx_exporter protmetheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(kafka_controller_kafkacontroller_controllerstate, job)"
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": "label_values(kafka_controller_kafkacontroller_controllerstate{job=\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_cluster_partition_replicascount{job=\"$job\"}, topic)"
   },
   {
    "name": "online_broker",
    "query": "query_result(count(up{job=~\"$job\"}))"
   }
  ]
 },
 "panels": [
  {
   "title": "Kafka Cluster health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Controller and Followers ",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Partitions Leader and Replica Per Broker",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_leadercount{job=~\"$job\"}"
    },
    {
     "expr": "count(kafka_cluster_partition_replicascount{job=\"$job\"} <= 1)by(instance)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\",topic=\"\"}[1m]))",
     "legendFormat": "Sum Total messages in per sec"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\",topic=\"\"}[$__range]))",
     "legendFormat": "Total messages from ${__from:date:MM-DD hA} to ${__to:date:MM-DD hA}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kafka_network_socketserver_networkprocessoravgidlepercent{job=\"$job\",instance=~\"$broker\"}*100)",
     "legendFormat": "Network processor avg {{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Request Handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "gauge",
     "description": "If <= 0 is very idle",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 64 },
     "repeat": "broker",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - rate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count{job=\"$job\",instance=~\"$broker\"}[1m]) / 10000000",
       "legendFormat": "Request handler avg {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(request)",
       "legendFormat": "Total {{request}} 99th"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(request)",
       "legendFormat": "Total {{request}} 99th"
      }
     ]
    },
    {
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(request)",
       "legendFormat": "Total {{request}} 99th"
      }
     ]
    },
    {
     "title": "Produce Latency 99th per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"Produce\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FetchConsumer Latency 99th per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchConsumer\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FetchFollow Latency 99th per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg (kafka_network_requestmetrics_totaltimems{request=\"FetchFollower\",job=\"$job\",quantile=\"0.99\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sort(sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"$job\",instance=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[1m]))by(topic))",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$job\",topic!=\"\",instance=~\"$broker\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_totalproducerequests_total{job=\"$job\",instance=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"$job\",instance=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Produce Request Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requests_total{request=~\"Produce\",job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "Request: {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"$job\",instance=~\"$broker\",topic!=\"\"}[1m]))by(instance)",
     "legendFormat": "Bytes Out [{{instance}}]"
    },
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$job\",instance=~\"$broker\",topic!=\"\"}[1m]))by(instance)",
     "legendFormat": "Bytes In [{{instance}}]"
    }
   ]
  },
  {
   "title": "Kafka Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Failed Produce Request Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{job=~\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Fetch Request Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{job=~\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Produce Request Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{job=~\"$job\",topic!=\"\",instance=~\"$broker\",topic=~\"$topic\"}[1m]))by(topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Failed Fetch Request Per Topic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{job=~\"$job\",topic!=\"\",instance=~\"$broker\",topic=~\"$topic\"}[1m]))by(topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Disconnects Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperdisconnects_total{job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Expires Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum (irate(kafka_server_sessionexpirelistener_zookeeperexpires_total{job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Request Latency Ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{job=\"$job\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Broker: {{instance}}"
      }
     ]
    },
    {
     "title": "Isr Shrinks / Isr Expands Per Sec",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum (irate(kafka_server_replicamanager_isrshrinks_total{job=\"$job\",instance=~\"$broker\"}[1m]))",
       "legendFormat": "ISR Shrinks Per Sec"
      },
      {
       "expr": "sum (irate(kafka_server_replicamanager_isrexpands_total{job=\"$job\",instance=~\"$broker\"}[1m]))",
       "legendFormat": "ISR Expands Per Sec"
      }
     ]
    },
    {
     "title": "FetchFollower Request Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_requests_total{request=~\"FetchFollower\",job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
       "legendFormat": "Request: {{instance}}"
      }
     ]
    },
    {
     "title": "FetchConsumer Request Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(kafka_network_requestmetrics_requests_total{request=\"FetchConsumer\",job=\"$job\",instance=~\"$broker\"}[5m]))by(instance)",
       "legendFormat": "Request: {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Requests Waiting in the Fetch Purgatory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{job=\"$job\",delayedOperation=\"Fetch\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Broker {{instance}}"
      }
     ]
    },
    {
     "title": "Total Fetch Request Per Broker",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum (irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{job=\"$job\",instance=~\"$broker\",topic!=\"\"}[1m]))by(instance)",
       "legendFormat": "Broker: {{instance}}"
      }
     ]
    },
    {
     "title": "Log Flush Stats Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum (irate(kafka_log_logflushstats_logflushrateandtimems_count{job=\"$job\",instance=~\"$broker\"}[5m]))by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Requests Waiting in the Producer Purgatory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{job=\"$job\",delayedOperation=\"Produce\",instance=~\"$broker\"})by(instance)",
       "legendFormat": "Broker {{instance}}"
      }
     ]
    },
    {
     "title": "Leader Election Rate Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (irate(kafka_controller_controllerstats_leaderelectionrateandtimems_count{job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "Partitions Leader Per Broker",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 128 },
     "targets": [
      {
       "expr": "kafka_cluster_partition_replicascount{job=~\"$job\",topic=~\"$topic\"}"
      }
     ]
    },
    {
     "title": "Disk Usage Segment Size",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
     "targets": [
      {
       "expr": "sort(sum(kafka_log_log_size{job=~\"$job\",instance=~\"$broker\"})by(instance))",
       "legendFormat": "Instance Broker:  {{instance}}"
      }
     ]
    },
    {
     "title": "Count Partition per Broker",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 145 },
     "targets": [
      {
       "expr": "sort(sum(kafka_server_replicamanager_partitioncount{job=~\"$job\"}) by (instance))",
       "legendFormat": "Instance Broker: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JVM Threads Current",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"$job\",instance=~\"$broker\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"$job\",instance=~\"$broker\"} )",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$broker\"}[5m])",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$job\",instance=~\"$broker\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Cassandra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Cassandra Memtable Metrics",
   "type": "timeseries",
   "description": "Memtable Metrics",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "cassandra_columnfamily_memtablelivedatasize",
     "legendFormat": "__auto"
    },
    {
     "expr": "cassandra_columnfamily_memtableonheapsize",
     "legendFormat": "__auto"
    },
    {
     "expr": "cassandra_columnfamily_memtableoffheapsize",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cassandra Connections",
   "type": "timeseries",
   "description": "General System Metrics",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients",
     "legendFormat": "__auto"
    },
    {
     "expr": "cassandra_client_pausedconnections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cassandra Reads and Writes",
   "type": "timeseries",
   "description": "Reads and Writes",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "cassandra_columnfamily_bytesflushed",
     "legendFormat": "__auto"
    },
    {
     "expr": "cassandra_commitlog_completedtasks",
     "legendFormat": "__auto"
    },
    {
     "expr": "cassandra_compaction_completedtasks",
     "legendFormat": "__auto"
    },
    {
     "expr": "cassandra_columnfamily_rowcachehit",
     "legendFormat": "__auto"
    },
    {
     "expr": "cassandra_columnfamily_rowcachemiss",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Spark Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Spark Non-Heap Committed & Used",
   "type": "timeseries",
   "description": "Non-Heap Committed & Used",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_jvm_non_heap_committed_Number\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_jvm_non_heap_used_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Heap Committed & Max",
   "type": "timeseries",
   "description": "Heap Committed & Max",
   "gridPos": { "h": 11, "w": 8, "x": 6, "y": 87 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_jvm_heap_committed_Number\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_jvm_heap_max_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Heap Used Number",
   "type": "timeseries",
   "description": "Heap Used Number",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 87 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_jvm_heap_used_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor Records Read/Written",
   "type": "timeseries",
   "description": "Records Read & Written",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_executor_recordsRead_Count\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_executor_recordsWritten_Count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor Bytes Read & Written",
   "type": "timeseries",
   "description": "Bytes Read & Written",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 98 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_executor_bytesRead_Count\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_executor_bytesWritten_Count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor DirectPool Memory",
   "type": "timeseries",
   "description": "DirectPool Memory",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 98 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_ExecutorMetrics_DirectPoolMemory_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor Off Heap Execution & Storage Memory",
   "type": "timeseries",
   "description": "Off Heap Execution & Storage Memory",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 98 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_ExecutorMetrics_OffHeapExecutionMemory_Number\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_ExecutorMetrics_OffHeapStorageMemory_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor Threadpool Completed Tasks",
   "type": "timeseries",
   "description": "Number of Completed Tasks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_executor_threadpool_completeTasks_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor Threadpool Active Tasks",
   "type": "timeseries",
   "description": "Number of Active Tasks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_executor_threadpool_activeTasks_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor Major GC Count",
   "type": "timeseries",
   "description": "GC Count",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_ExecutorMetrics_MajorGCCount_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor Major GC Time",
   "type": "timeseries",
   "description": "Major GC Time",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 116 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_ExecutorMetrics_MajorGCTime_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor Minor GC Count",
   "type": "timeseries",
   "description": "Minor GC Count",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 116 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_ExecutorMetrics_MinorGCCount_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor Minor GC Time",
   "type": "timeseries",
   "description": "Minor GC Time",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_ExecutorMetrics_MinorGCTime_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor Total GC Time",
   "type": "timeseries",
   "description": "Total GC Time",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 116 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_ExecutorMetrics_TotalGCTime_Number\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spark Executor CPU Time",
   "type": "timeseries",
   "description": "CPU Time",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 116 },
   "targets": [
    {
     "expr": "{__name__=~\"metrics_local_.*_driver_executor_cpuTime_Count\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}